### PR TITLE
Jetty 9 Fix

### PR DESCRIPTION
**Pull request by JoseGrangerSalgado**

### CODE REVIEW

**Review by josueetcom — COMMENTED** [review]
What is wrong with Jetty 11?

**Review by josueetcom — APPROVED** [review]
Nvm, I just saw the email 👍

**Comment by josueetcom** [comment]
> Nvm, I just saw the email 👍

For future reference, it helps to provide a description explaining the reason for changes like these 🙂

**Comment by JoseGrangerSalgado** [comment]
Okay, I'll make sure to specify next time. Thank you.

**Pull request merged**
